---
title: エラーの処理方法
nav_title: エラー処理
slug: /docs/app/getting-started/error-handling
description: 予期されるエラーの表示と未捕捉の例外の処理方法について学びます。
related:
  title: APIリファレンス
  description: このページで言及された機能についてさらに詳しく学ぶには、APIリファレンスをお読みください。
  links:
    - app/api-reference/functions/redirect
    - app/api-reference/file-conventions/error
    - app/api-reference/functions/not-found
    - app/api-reference/file-conventions/not-found
---

エラーは[予期されるエラー](#handling-expected-errors)と[未捕捉の例外](#handling-uncaught-exceptions)の2つのカテゴリに分けることができます。このページではNext.jsアプリケーションでこれらのエラーを処理する方法を説明します。

## 予期されるエラーの処理

予期されるエラーとは、[サーバーサイドのフォームバリデーション](/docs/app/building-your-application/data-fetching/server-actions-and-mutations#server-side-form-validation)やリクエストの失敗など、アプリケーションの通常の操作中に発生する可能性のあるエラーです。これらのエラーは明示的に処理し、クライアントに返す必要があります。

### Server Actions

[`useActionState`](https://react.dev/reference/react/useActionState)フックを使用して[Server Functions](https://react.dev/reference/rsc/server-functions)の状態を管理し、予期されるエラーを処理できます。予期されるエラーには`try`/`catch`ブロックを使用しないでください。代わりに、予期されるエラーはスローされる例外ではなく、戻り値としてモデル化できます。

```ts filename="app/actions.ts" switcher
'use server'

export async function createPost(prevState: any, formData: FormData) {
  const title = formData.get('title')
  const content = formData.get('content')

  const res = await fetch('https://api.vercel.app/posts', {
    method: 'POST',
    body: { title, content },
  })
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Failed to create post' }
  }
}
```

```js filename="app/actions.js" switcher
'use server'

export async function createPost(prevState, formData) {
  const title = formData.get('title')
  const content = formData.get('content')

  const res = await fetch('https://api.vercel.app/posts', {
    method: 'POST',
    body: { title, content },
  })
  const json = await res.json()

  if (!res.ok) {
    return { message: 'Failed to create post' }
  }
}
```

そして、アクションを`useActionState`フックに渡し、返された`state`を使用してエラーメッセージを表示できます。

```tsx filename="app/ui/form.tsx" highlight={11,19} switcher
'use client'

import { useActionState } from 'react'
import { createPost } from '@/app/actions'

const initialState = {
  message: '',
}

export function Form() {
  const [state, formAction, pending] = useActionState(createPost, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="title">Title</label>
      <input type="text" id="title" name="title" required />
      <label htmlFor="content">Content</label>
      <textarea id="content" name="content" required />
      {state?.message && <p aria-live="polite">{state.message}</p>}
      <button disabled={pending}>Create Post</button>
    </form>
  )
}
```

```jsx filename="app/ui/form.js" highlight={11,19} switcher
'use client'

import { useActionState } from 'react'
import { createPost } from '@/app/actions'

const initialState = {
  message: '',
}

export function Form() {
  const [state, formAction, pending] = useActionState(createPost, initialState)

  return (
    <form action={formAction}>
      <label htmlFor="title">Title</label>
      <input type="text" id="title" name="title" required />
      <label htmlFor="content">Content</label>
      <textarea id="content" name="content" required />
      {state?.message && <p aria-live="polite">{state.message}</p>}
      <button disabled={pending}>Create Post</button>
    </form>
  )
}
```

### Server Components

Server Component内でデータをフェッチする場合、レスポンスを使用して条件付きでエラーメッセージをレンダリングしたり、[`redirect`](/docs/app/api-reference/functions/redirect)したりできます。

```tsx filename="app/page.tsx" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```

```jsx filename="app/page.js" switcher
export default async function Page() {
  const res = await fetch(`https://...`)
  const data = await res.json()

  if (!res.ok) {
    return 'There was an error.'
  }

  return '...'
}
```

### Not found

ルートセグメント内で[`notFound`](/docs/app/api-reference/functions/not-found)関数を呼び出し、[`not-found.js`](/docs/app/api-reference/file-conventions/not-found)ファイルを使用して404 UIを表示できます。

```tsx filename="app/blog/[slug]/page.tsx" switcher
import { getPostBySlug } from '@/lib/posts'

export default async function Page({ params }: { params: { slug: string } }) {
  const post = getPostBySlug((await params).slug)

  if (!post) {
    notFound()
  }

  return <div>{post.title}</div>
}
```

```jsx filename="app/blog/[slug]/page.js" switcher
import { getPostBySlug } from '@/lib/posts'

export default async function Page({ params }) {
  const post = getPostBySlug((await params).slug)

  if (!post) {
    notFound()
  }

  return <div>{post.title}</div>
}
```

```tsx filename="app/blog/[slug]/not-found.tsx" switcher
export default function NotFound() {
  return <div>404 - Page Not Found</div>
}
```

```jsx filename="app/blog/[slug]/not-found.js" switcher
export default function NotFound() {
  return <div>404 - Page Not Found</div>
}
```

## 未捕捉の例外の処理

未捕捉の例外は、アプリケーションの通常のフローでは発生しないはずのバグや問題を示す予期しないエラーです。これらはエラーをスローすることで処理され、そのエラーはエラーバウンダリによって捕捉されます。

### ネストされたエラーバウンダリ

Next.jsは未捕捉の例外を処理するためにエラーバウンダリを使用します。エラーバウンダリは子コンポーネントのエラーを捕捉し、クラッシュしたコンポーネントツリーの代わりにフォールバックUIを表示します。

ルートセグメント内に[`error.js`](/docs/app/api-reference/file-conventions/error)ファイルを追加し、Reactコンポーネントをエクスポートすることでエラーバウンダリを作成できます：

```tsx filename="app/dashboard/error.tsx" switcher
'use client' // エラーバウンダリはクライアントコンポーネントである必要があります

import { useEffect } from 'react'

export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  useEffect(() => {
    // エラーをエラー報告サービスに記録する
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みる
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```

```jsx filename="app/dashboard/error.js" switcher
'use client' // エラーバウンダリはクライアントコンポーネントである必要があります

import { useEffect } from 'react'

export default function Error({ error, reset }) {
  useEffect(() => {
    // エラーをエラー報告サービスに記録する
    console.error(error)
  }, [error])

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // セグメントの再レンダリングを試みて回復を試みる
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  )
}
```

エラーは最も近い親のエラーバウンダリにバブルアップします。これにより、[ルート階層](/docs/app/getting-started/project-structure#component-hierarchy)の異なるレベルに`error.tsx`ファイルを配置することで、きめ細かいエラー処理が可能になります。

<Image
  alt="ネストされたエラーコンポーネント階層"
  srcLight="/light/nested-error-component-hierarchy.png"
  srcDark="/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

### グローバルエラー

あまり一般的ではありませんが、[国際化](/docs/app/building-your-application/routing/internationalization)を活用する場合でも、ルートappディレクトリにある[`global-error.js`](/docs/app/api-reference/file-conventions/error#global-error)ファイルを使用して、ルートレイアウトのエラーを処理できます。グローバルエラーUIは、アクティブな場合にルートレイアウトまたはテンプレートを置き換えるため、独自の`<html>`タグと`<body>`タグを定義する必要があります。

```tsx filename="app/global-error.tsx" switcher
'use client' // エラーバウンダリはクライアントコンポーネントである必要があります

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string }
  reset: () => void
}) {
  return (
    // global-errorはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```

```jsx filename="app/global-error.js" switcher
'use client' // エラーバウンダリはクライアントコンポーネントである必要があります

export default function GlobalError({ error, reset }) {
  return (
    // global-errorはhtmlとbodyタグを含める必要があります
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  )
}
```
